version: '3.8'

services:
  myapp:
    build: .
    ports:
      - "5000:80"  # 映射容器的端口 80 到主機的端口 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDatabase;User=sa;Password=YourStrong@Passw0rd;
    depends_on:
      - sqlserver

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"  # 映射 Jenkins 的端口
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  jenkins_home:
  sqlserver_data:
