version: '3.9'

services:
  myapp:
    build: .
    ports:
      - "5000:80"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDatabase;User=sa;Password=YourStrong@Passw0rd;
    volumes:
      - /c/Users/User/Desktop:/shared_data
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - /c/Users/User/Desktop:/shared_data
    networks:
      - mynetwork

  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/User/Desktop:/shared_data
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - mynetwork

volumes:
  sqlserver_data:
  jenkins_home:

networks:
  mynetwork:
